#application.yml 可以用来定义应用级别的，
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/sys_user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull'
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: 'classpath*:mapper/*Mapper.xml'   